portaljob/portaljob/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('portaljob_visitor.urls') ),
    path('admin/', admin.site.urls),
    path('register/',include('registration.urls')),
    path('main_app/',include('portaljob_activity.urls')),
]

portaljob/portaljob_activity/urls.py
from django.urls import path
from . import views

app_name='portaljob_activity'
urlpatterns = [
    path('',views.index, name='index')
]

portaljob/portaljob_visitor/urls.py
from django.urls import path

from . import views

app_name='portaljob_visitor'

urlpatterns = [
    path('', views.index, name='index'),
    path('recruitment',views.recruitment, name='recruitment')
]

portaljob/registration/urls.py
from django.urls import path
from . import views

app_name='registration'

urlpatterns = [
    path('login/',views.login, name="login"),
    # path('signup/',views.signup, name="signup"),
    path('logout/',views.logout, name="logout"),
]

portaljob/portaljob_activity/models.py
from django.db import models
from datetime import datetime,date
from registration.models import User

# Create your models here.

class Administration(models.Model):
    coverage_photo=models.ImageField(upload_to='portaljob_activity')

class Recruitment_info(models.Model):
    name=models.CharField(max_length=200,default='')
    pub_date=models.DateField('date de publication',default='')
    user_id=models.ForeignKey(User, on_delete=models.CASCADE)
    end_recruitment_date=models.DateField('Fin de recruitement',default='')
    description=models.TextField('Description on the job',default='')
    def __str__(self):
        return self.name

portaljob/portaljob_visitor/models.py
from django.db import models

# Create your models here.

portaljob/portaljob_activity/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def index(request):
    return render(request, 'portaljob_activity/index.html')

portaljob/portaljob_visitor/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'portaljob_visitor/index.html')

def recruitment(request):
    return render(request,'portaljob_visitor/recruitment.html')

portaljob/portaljob_activity/templates/portaljob_activity/index.html
{%extends 'base.html'%}
{%block is_authenticated%}
    <a class="nav-link" href="#">All post</a>
    <a class="nav-link" href="#">New career</a>
{%endblock %}

portaljob/portaljob_visitor/templates/portaljob_visitor/index.html
{%extends 'base.html'%}

{%block title%}
    PortalJob
{%endblock %}

{%block content%}
<!-- <span> -->
    <section class="offre_recrutment">
        <div id="offre_recrutement">
            <div class="d-flex justify-content-center">
                <h2 class="mt-3">Nos offre d'emplois</h2>
            </div>
            <div class="row" style="margin:10px;">
                <!-- eto card 1 dia atao card 8 isak mandeha -->
                <div class="col-sm-3 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-primary w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <!-- hatreto -->

                <div class="col-sm-3 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-primary w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-primary w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-primary w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-primary w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-primary w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-primary w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-primary w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                
            </div>

            <div class="d-flex justify-content-center">
                <a href="#">Voir toutes les offres d'emplois</a>
            </div>
        </div>
          
        <!-- <hr style="margin:auto; width:80%"> -->

        <div id="offre_formation">
            <div class="d-flex justify-content-center">
                <h2 class="mt-3">Les derniere formations</h2>
            </div>

            <div class="row " style="margin:10px;">
                <!-- eto card 1 dia atao card 8 isak mandeha -->
                <div class="col-sm-6 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-info w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <!-- Hatreto -->
                <!-- eto card 1 dia atao card 8 isak mandeha -->
                <div class="col-sm-6 mp-2 mt-1 mb-1" >
                    <div class="card" style="border-radius: 20px;">
                        <div class="card-body">
                            <!-- date de publication -->
                            <span class="card-subtitle d-flex justify-content-center">Date de publication</span>
                            <!-- title -->
                            <h5 class="card-title">Dev Django</h5>
                            <!-- description -->
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <!-- date de fin de recrutement -->
                            <span class="card-subtitle d-flex justify-content-center mb-2">Date de fin de publication</span>
                            <!-- link to post -->
                            <a href="#" class="btn btn-info w-100">Postuler</a>
                        </div>
                    </div>
                </div>
                <!-- Hatreto -->
            </div>

            <div class="d-flex justify-content-center">
                <a href="#">Voir toutes les formations</a>
            </div>
        </div>
    </section>
<!-- </span> -->
{% endblock %}

portaljob/portaljob_visitor/templates/portaljob_visitor/recruitment.html
{%extends 'base.html'%}

{%block title%}
Recruitment
{%endblock %}

{%block content%}
    this is a recruitment
{%endblock %}

portaljob/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .parallax {
        /* The image used */
        background-image: url("https://jooinn.com/images/abstract-background-345.jpg");

        /* Set a specific height */
        min-height: 250px; 

        /* Create the parallax scrolling effect */
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        }
    </style>
    <title>
        {%block title%}
        {%endblock %}
    </title>
</head>
<body style="font-family: 'lato'">
    <div class="main">
        

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid d-flex">
                <a class="navbar-brand" style="margin-left:30px" href="{%url 'portaljob_visitor:index'%}">Portal job</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            {%block is_authenticated%}
                            {%endblock %}
                        {% else %}
                            <a class="nav-link active" aria-current="page" href="{%url 'portaljob_visitor:recruitment'%}">Emplois</a>
                            <a class="nav-link" href="#">Profils</a>
                            <a class="nav-link" href="#">Formations</a>
                            <a class="nav-link" href="#">Contacts</a>
                        {% endif %}
                        
                        <!-- <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
                    </div>
                </div>
                
                {% if user.is_authenticated == False%}
                    <div class="collapse navbar-collapse d-flex justify-content-end navbar-nav">
                        <a class="nav-link link-secondary" href="{%url 'registration:login'%}">Connexion</a>
                    </div>
                {% else %}
                    <div class="collapse navbar-collapse d-flex justify-content-end navbar-nav">
                        <a class="nav-link link-secondary" href="{%url 'registration:logout'%}">Déconexion</a>
                    </div>
                {%endif%}

            </div>
        </nav>
        <!-- <div class=""></div> -->
        {% if user.is_authenticated == False%}
            <section class="header-main border-bottom  parallax">
                <div class="container-fluid">
                    <div class="row p-2 pt-3 pb-3 d-flex align-items-center">
                        <div class="col-md-2" style="text-align: center;"> 
                            <span>
                                Rechercher Emplois et recrutement
                            </span>
                            <!-- <img class="d-none d-md-flex" src="https://i.imgur.com/R8QhGhk.png" width="100">  -->
                        </div>
                        <div class="col-md-8">
                            <div class="d-flex form-inputs"> <input class="form-control" type="text" placeholder=" Recherche de Mots cles" style="margin-left:20px;"> <i class="bx bx-search"></i> </div>
                        </div>
                        <!-- <div class="col-md-2">
                            <div class="d-flex d-none d-md-flex flex-row align-items-center"> <span class="shop-bag"><i class='bx bxs-shopping-bag'></i></span>
                                <div class="d-flex flex-column ms-2"> <span class="qty">1 Product</span> <span class="fw-bold">$27.90</span> </div>
                            </div>
                        </div> -->
                    </div>
                </div>
            </section>      
        {%endif%}

        
        {%block content%}
        {%endblock %}
        <!-- footer begin -->
        <!-- Footer -->
        <footer class="text-center text-lg-start bg-light text-muted mt-4"  >
        <!-- Section: Social media -->
        <section
            class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
        >
            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
            </div>
            <!-- Left -->

            <!-- Right -->
            <div>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-github"></i>
            </a>
            </div>
            <!-- Right -->
        </section>
        <!-- Section: Social media -->

        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold mb-4">
                    <i class="fas fa-gem me-3"></i>Company name
                </h6>
                <p>
                    Here you can use rows and columns to organize your footer content. Lorem ipsum
                    dolor sit amet, consectetur adipisicing elit.
                </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                    Products
                </h6>
                <p>
                    <a href="#!" class="text-reset">Angular</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">React</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Vue</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Laravel</a>
                </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                    Useful links
                </h6>
                <p>
                    <a href="#!" class="text-reset">Pricing</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Settings</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Orders</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Help</a>
                </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                    Contact
                </h6>
                <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                <p>
                    <i class="fas fa-envelope me-3"></i>
                    info@example.com
                </p>
                <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->

        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2021 Copyright:
            <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
        </footer>
        <!-- Footer -->
    </div>
</body>
</html>